### ISSUE TITLE
DeepLabv3plus+Mobilenetv2-HighLevelDemo on semantic segmentation doesn't work

### ISSUE THREAD

**Issue by saarijoki** [luxonis/depthai-ml-training#3]
Hi,

Running the last step of the Google Colab example for semantic segmentation gives me the following error:

`[setupvars.sh] OpenVINO environment initialized
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/content/l_openvino_toolkit_p_2020.1.023/models/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set_mobilenetv2/export/frozen_inference_graph.pb
	- Path for generated IR: 	/content/
	- IR output name: 	deeplab_v3_plus_mnv2_decoder_256.pb
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,256,256,3]
	- Mean values: 	[127.5, 127.5, 127.5]
	- Scale values: 	[127.5, 127.5, 127.5]
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	True
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Operations to offload: 	None
	- Patterns to offload: 	None
	- Use the config file: 	None
Model Optimizer version: 	2020.1.0-61-gd349c3ba4a
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.back.ConvolutionNormalizer.PullReshapeThroughFQ'>): After partial shape inference were found shape collision for node strided_slice_10/Cast_2 (old shape: [3], new shape: [4])
[ ]
`

I was promised a semantic segmentation example with depth perception upon backing up the OAK-D but now I can't find even one working example of any kind of semantic segmentation model. :(

**Comment by Luxonis-Brandon** [comment]
Hi @saarijoki ,

Sorry about the delay and the trouble here.  

So you don't actually have to use this training to get semantic segmentation and depth on OAK-D.  

Here is the command using the depthai demo program for the Gen1 API, [here](https://github.com/luxonis/depthai):
`python3 depthai_demo.py -cnn deeplabv3_person`

![image](https://user-images.githubusercontent.com/32992551/107603253-599dd500-6be9-11eb-9368-a953659ab0e6.png)

And actually we wrote a Gen2 example recently, which I will find and share here.  And there's also a Gen2 example that aligns the RGB onto depth so you can run semantic segmentation on the RGB camera and have it overlaid on the depth (instead of having to run on the grayscale camera).

**Comment by Luxonis-Brandon** [comment]
And while I pull that up, SuperAnnotate also has an updated tutorial for training a customer Deeplabv3+ model, see here:
[https://github.com/superannotateai/model-deployment-tutorials/blob/main/OAK/SuperAnnotate_OAK_Deeplabv3%2B_Deployment.ipynb](https://github.com/superannotateai/model-deployment-tutorials/blob/main/OAK/SuperAnnotate_OAK_Deeplabv3%2B_Deployment.ipynb)

Thoughts?  

And sorry about the delay...  most of my day-time these days is consumed with shipping/logistics issues with floship, so I only get to the technical things during the night hours.  Will circle back with more details soon as well.

**Comment by Luxonis-Brandon** [comment]
Here is the Gen2 API demo:
[https://github.com/luxonis/depthai-experiments/pull/63](https://github.com/luxonis/depthai-experiments/pull/63)

![image](https://user-images.githubusercontent.com/32992551/107603650-a7670d00-6bea-11eb-9408-57d4ee31485d.png)

**Comment by Luxonis-Brandon** [comment]
I'll circle back tomorrow with more examples of how to run deeplabv3+ on the grayscale (right) camera as well.  I can't seem to find it right now and need to get more shipping updates out about the 250 shipments stuck in Germany.

Thanks,
Brandon

**Comment by Luxonis-Brandon** [comment]
Here is running on grayscale with deeplabv3+ with the Gen1 API:

`python3 depthai_demo.py -cnn deeplabv3p_person -cam right`

![image](https://user-images.githubusercontent.com/32992551/107604534-a7b4d780-6bed-11eb-8976-fa0272a548db.png)

**Comment by Luxonis-Brandon** [comment]
And here is running on both left and right in parallel:
`python3 depthai_demo.py -cnn deeplabv3p_person -cam left_right`
![image](https://user-images.githubusercontent.com/32992551/107604638-f3678100-6bed-11eb-9725-5173752ae8b0.png)

And here is with the option to put the full aspect ration of the frame (`-ff`) into the neural network, so that the whole FOV of the camera is seen by the 1:1 aspect ration deeplab network:

`python3 depthai_demo.py -cnn deeplabv3p_person -cam left_right -ff`
![image](https://user-images.githubusercontent.com/32992551/107604791-64a73400-6bee-11eb-9148-30bf9910238c.png)

**Comment by Luxonis-Brandon** [comment]
And we just updated the Gen2 example to allow left/right/RGB inference via CLI option as well:
https://github.com/luxonis/depthai-experiments/pull/63/commits/6c2e9b20af4d6c3df00e233935d51e18295bd5a1

`python3 -m pip install -r requirements.txt`
`python3 deeplabv3_person_256.py -cam right` (or left or right)

**Comment by saarijoki** [comment]
Whoa! Thanks, these look really cool and the examples work nicely. :)
I now just need to figure out a way to utilize the SuperAnnotate example with my CVAT annotations and I should be good to go.
