### ISSUE TITLE
YoloV6 pt to blob converter tool not working

### ISSUE THREAD

**Issue by thehummingbird** [luxonis/depthai-ml-training#38]
I'm using [this](https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/YoloV6_training.ipynb) colab notebook to train a YoloV6N model.

As shown in the notebook, I train my model and then download my pytorch weights. I then use the online tool to convert it to blob format, which is failing (as shown below). Pt weights [here](https://drive.google.com/drive/folders/1korEZae1GmrgIIBrJHkVrrfZ1Npa_-vN?usp=share_link)

I've also tried "640 352" in the field "Input Shape", but to no avail.

![yolopttoblob](https://user-images.githubusercontent.com/12541976/214237252-3aaf29aa-58b9-4cfe-b578-fcc22064822d.png)

**Comment by tersekmatija** [comment]
@HonzaCuhel is this related to the PR [here](https://github.com/luxonis/tools/pull/29) which was deployed today?

**Comment by HonzaCuhel** [comment]
@tersekmatija yes, it looks like it. I have tried to convert the model weights myself, and it worked. I tried both shapes, "640" and "640 352".

@thehummingbird, please try to convert your weights again. It should work now. Today we have deployed an updated version of our tools, adding support for YoloV6 R3 (so that's probably why it wasn't previously working).

**Comment by thehummingbird** [comment]
It now works. Thank you guys!

**Comment by HonzaCuhel** [comment]
Awesome, glad to hear that!
