### ISSUE TITLE
Converted YOLO model doesn't show any outputs

### ISSUE THREAD

**Issue by TannerGilbert** [luxonis/depthai-ml-training#4]
I converted a yolo-v3-tiny model to OpenVINO and then to a .blob file as shown in [Easy_TinyYolov3_Object_Detector_Training_on_Custom_Data.ipynb](https://github.com/luxonis/depthai-ml-training/blob/master/colab-notebooks/Easy_TinyYolov3_Object_Detector_Training_on_Custom_Data.ipynb), but even though I don't receive any error messages when I try to use the mode as described in the [To run the .blob in DepthAI section](https://colab.research.google.com/github/luxonis/depthai-ml-training/blob/master/colab-notebooks/Easy_TinyYolov3_Object_Detector_Training_on_Custom_Data.ipynb#scrollTo=FKsBJxsNxb9u&line=1&uniqifier=1), it doesn't show any output.

My notebook: https://colab.research.google.com/drive/1Kt-ESQ-0wpemo2Bg7AefI6qL3Xt374jp?usp=sharing

**Comment by Luxonis-Brandon** [comment]
Hi @TannerGilbert ,

Sorry about the delay.  I'm not immediately sure, but this actually sounds familiar, and I can't quite place it.

I'm asking if @Erol444 can help.

Thanks,
Brandon

**Comment by Erol444** [comment]
Hello @TannerGilbert,
so the first thing would probably be to use a newer OpenVINO version (2021.2). Looking at [our tiny yolo V3 demo](https://docs.luxonis.com/projects/api/en/latest/samples/22_tiny_tolo_v3_decoding_on_device/), it was compiled using 2021.2.
You should also use the depthAI **gen2**. In the demo mentioned above (it's gen2), we can have yoloV3 output decoded on the device side.
Thanks, Erik

**Comment by TannerGilbert** [comment]
Just tried to change to OpenVINO 2021 by changing the download but it seems that other changes are also required. Would you mind updating the [Easy_TinyYolov3_Object_Detector_Training_on_Custom_Data.ipynb](Easy_TinyYolov3_Object_Detector_Training_on_Custom_Data.ipynb) and [Easy_TinyYOLOv4_Object_Detector_Training_on_Custom_Data.ipynb](https://github.com/luxonis/depthai-ml-training/blob/master/colab-notebooks/Easy_TinyYOLOv4_Object_Detector_Training_on_Custom_Data.ipynb) notebooks to work with OpenVINO version (2021.2).

**Comment by Luxonis-Brandon** [comment]
Yes, good idea.  Will do @Erol444 could you help on this?  (And sorry for the trouble here @TannerGilbert .)

**Comment by Erol444** [comment]
Hello @TannerGilbert 
sorry for the late reply. I played with it a bit and it seems to be working for me, the yoloV3 example. I did however used the latest OpenVINO (2021.2).

**so steps that I did differently:**
- When installing openvino, the link is https://registrationcenter-download.intel.com/akdlm/irc_nas/17504/l_openvino_toolkit_p_2021.2.185.tgz (this also changes the correct paths later on)
- I used default images, so don't delete the folder containing the images/labels
- When converting IR to blob, this is the code I used:
```
blob_dir = "/content/yolotinyv3_medmask_demo/TinyIR/"
binfile = "/content/yolotinyv3_medmask_demo/TinyIR/frozen_darknet_yolov3_model.bin"
xmlfile = "/content/yolotinyv3_medmask_demo/TinyIR/frozen_darknet_yolov3_model.xml"

import requests

url = "http://69.164.214.171:8083/compile"  # change if running against other URL

payload = {
    'compiler_params': '-ip U8 -VPU_NUMBER_OF_SHAVES 8 -VPU_NUMBER_OF_CMX_SLICES 8',
    'compile_type': 'myriad'
}
files = {
    'definition': open(xmlfile, 'rb'),
    'weights': open(binfile, 'rb')
}
params = {
# When will 2021.2 available?
    'version': '2021.1',  # OpenVINO version, can be "2021.1", "2020.4", "2020.3", "2020.2", "2020.1", "2019.R3"
}

response = requests.post(url, data=payload, files=files, params=params)
blobnameraw = response.headers.get('Content-Disposition')
print(blobnameraw)
print(response.status_code) 

blobname = blobnameraw[blobnameraw.find('='):][1:]
with open(blob_dir + blobname, 'wb') as f:
  f.write(response.content)
```
- I used this [demo code](https://docs.luxonis.com/projects/api/en/latest/samples/22_tiny_tolo_v3_decoding_on_device/) and changed `label_map = ["mask", "no masks"] ` (line 18), `detectionNetwork.setNumClasses(2)` (line 41) and because I compiled for 2021.1 not 2021.2, also `pipeline.setOpenVINOVersion(dai.OpenVINO.Version.VERSION_2021_1)` (after line 29).

I will play around with it a bit more and change the demo where needed (& add docs) :)

**Comment by Erol444** [comment]
@TannerGilbert  I have also edited the YoloV3/YoloV4 notebooks so they match the comment above: https://github.com/luxonis/depthai-ml-training/pull/5

**Comment by TannerGilbert** [comment]
@Erol444 Thanks a lot. I'll close this issue for now.
